USE AIRLINE;

CREATE VIEW VIEW_AIRPLANE
AS
SELECT AP.ID AS AP_ID,
		AP.NAME AS AP_NAME,
        AP.SHORT_NAME AS AP_SHORT_NAME,
        AP.CAPACITY AS AP_CAPACITY,
        AP.STATE AS AP_STATE,
        AP.AL_ID AS AL_ID,
        AL.NAME AS AL_NAME
FROM AIRPLANE AP JOIN AIRLINE AL ON AP.AL_ID = AL.ID;

DELIMITER //
CREATE PROCEDURE VIEW_AIRPLANE_PAGE(IN STARTPAGE INT,IN LIMITPAGE INT)
BEGIN
SELECT AP.ID AS AP_ID,
		AP.NAME AS AP_NAME,
        AP.SHORT_NAME AS AP_SHORT_NAME,
        AP.CAPACITY AS AP_CAPACITY,
        AP.STATE AS AP_STATE,
        AP.AL_ID AS AL_ID,
        AL.NAME AS AL_NAME
FROM AIRPLANE AP JOIN AIRLINE AL ON AP.AL_ID = AL.ID
LIMIT STARTPAGE,LIMITPAGE;
END //
DELIMITER ;

CREATE VIEW VIEW_AIRPLANE_CHAIR
AS
SELECT APC.ID AS APC_ID,
		APC.QUANTITY AS APC_QUANTITY,
        APC.PRICE AS APC_PRICE,
        APC.USED AS APC_USED,
        APC.PLAY_DATE AS APC_DATE,
        APC.STATE AS APC_STATE,
        APC.AP_ID AS AP_ID,
        APC.C_ID AS C_ID,
        AP.NAME AS AP_NAME,
        AP.SHORT_NAME AS AP_SHORT_NAME,
        AP.CAPACITY AS AP_CAPACITY,
        C.NAME AS C_NAME
FROM AIRPLANE_CHAIR APC JOIN AIRPLANE AP ON APC.AP_ID = AP.ID
						JOIN CHAIR C ON APC.C_ID = C.ID;
    
DELIMITER //
CREATE PROCEDURE VIEW_AIRPLANE_CHAIR_PAGE(IN STARTPAGE INT,IN LIMITPAGE INT)
BEGIN
SELECT APC.ID AS APC_ID,
		APC.QUANTITY AS APC_QUANTITY,
        APC.PRICE AS APC_PRICE,
        APC.USED AS APC_USED,
        APC.PLAY_DATE AS APC_DATE,
        APC.STATE AS APC_STATE,
        APC.AP_ID AS AP_ID,
        APC.C_ID AS C_ID,
        AP.NAME AS AP_NAME,
        AP.SHORT_NAME AS AP_SHORT_NAME,
        AP.CAPACITY AS AP_CAPACITY,
        C.NAME AS C_NAME
FROM AIRPLANE_CHAIR APC JOIN AIRPLANE AP ON APC.AP_ID = AP.ID
						JOIN CHAIR C ON APC.C_ID = C.ID
LIMIT STARTPAGE,LIMITPAGE;
END //
DELIMITER ;
    
CREATE VIEW VIEW_FLIGHT
AS
SELECT F.ID AS F_ID,
		C.SHORT_NAME AS F_TO_CITY,
        F.TO_DATE_TIME AS F_TO_DATE,
		CS.SHORT_NAME AS F_FORM_CITY,
        F.FORM_DATE_TIME AS F_FORM_DATE,
        F.USED_CAPACITY AS F_USED_CAPACITY,
        F.STATE AS F_STATE,
        F.AP_ID AS AP_ID,
        AP.NAME AS AP_NAME,
        AP.SHORT_NAME AS AP_SHORT_NAME,
        AP.CAPACITY AS AP_CAPACITY
FROM FLIGHT F JOIN AIRPLANE AP ON F.AP_ID = AP.ID
		JOIN CITY C ON F.TO_CITY = C.ID JOIN CITY CS ON CS.ID = F.FORM_CITY;
        
DELIMITER //
CREATE PROCEDURE VIEW_FLIGHT_PAGE(IN STARTPAGE INT,IN LIMITPAGE INT)
BEGIN
SELECT F.ID AS F_ID,
		C.SHORT_NAME AS F_TO_CITY,
        F.TO_DATE_TIME AS F_TO_DATE,
		CS.SHORT_NAME AS F_FORM_CITY,
        F.FORM_DATE_TIME AS F_FORM_DATE,
        F.USED_CAPACITY AS F_USED_CAPACITY,
        F.STATE AS F_STATE,
        F.AP_ID AS AP_ID,
        AP.NAME AS AP_NAME,
        AP.SHORT_NAME AS AP_SHORT_NAME,
        AP.CAPACITY AS AP_CAPACITY
FROM FLIGHT F JOIN AIRPLANE AP ON F.AP_ID = AP.ID
		JOIN CITY C ON F.TO_CITY = C.ID JOIN CITY CS ON CS.ID = F.FORM_CITY
		LIMIT STARTPAGE,LIMITPAGE;
END //
DELIMITER ;
    
        
    
DELIMITER //
CREATE PROCEDURE VIEW_FLIGHT_DATE_CHAIR( IN FFORMCITY INT, IN FTOCITY INT, IN CID INT)
BEGIN
	SELECT F.ID AS F_ID,
			F.TO_CITY AS F_TO_CITY,
            F.TO_DATE_TIME AS F_TO_DATE,
            F.FORM_CITY AS F_FORM_CITY,
            F.FORM_DATE_TIME AS F_FORM_DATE,
            F.USED_CAPACITY AS F_USED_CAPACITY,
			F.AP_ID AS AP_ID,
            AP.NAME AS AP_NAME,
            AP.SHORT_NAME AS AP_SHORT_NAME,
            AP.CAPACITY AS AP_CAPACITY,
            AL.ID AS AL_ID,
            AL.NAME AS AL_NAME,
            AL.SHORT_NAME AS AL_SHORT_NAME,
            CT.NAME AS CT_NAME,
            CT.SHORT_NAME AS CT_SHORT_NAME,
            CTY.NAME AS CTY_NAME,
            CTY.SHORT_NAME AS CTY_SHORT_NAME,
            APC.ID AS APC_ID,
            APC.QUANTITY AS APC_QUANTITY,
            APC.PRICE AS APC_PRICE,
            APC.USED AS APC_USED,
            APC.PLAY_DATE AS APC_DATE,
            APC.C_ID AS C_ID,
            C.NAME AS C_NAME
	FROM FLIGHT F JOIN AIRPLANE AP ON F.AP_ID = AP.ID 
			JOIN AIRPLANE_CHAIR APC ON APC.AP_ID = AP.ID
            JOIN CHAIR C ON C.ID = APC.C_ID 
            JOIN CITY CT ON CT.ID = F.TO_CITY
            JOIN CITY CTY ON CTY.ID = F.FORM_CITY
            JOIN AIRLINE AL ON AL.ID = AP.AL_ID
	WHERE F.FORM_CITY = FFORMCITY 
		AND F.TO_CITY = FTOCITY 
		AND C.ID = CID
        AND CT.STATE = 1
        AND CTY.STATE = 1
        AND AL.STATE = 1
        AND AP.STATE = 1
        AND C.STATE = 1
        AND APC.STATE = 1;
END //
DELIMITER ;


DELIMITER //
CREATE PROCEDURE  VIEW_FLIGHT_DATE_CHAIR_BY_ID(IN FLIGHTID INT)
BEGIN
SELECT F.ID AS F_ID,
			F.TO_CITY AS F_TO_CITY,
            F.TO_DATE_TIME AS F_TO_DATE,
            F.FORM_CITY AS F_FORM_CITY,
            F.FORM_DATE_TIME AS F_FORM_DATE,
            F.USED_CAPACITY AS F_USED_CAPACITY,
			F.AP_ID AS AP_ID,
            AP.NAME AS AP_NAME,
            AP.SHORT_NAME AS AP_SHORT_NAME,
            AP.CAPACITY AS AP_CAPACITY,
            AL.ID AS AL_ID,
            AL.NAME AS AL_NAME,
            AL.SHORT_NAME AS AL_SHORT_NAME,
            CT.NAME AS CT_NAME,
            CT.SHORT_NAME AS CT_SHORT_NAME,
            CTY.NAME AS CTY_NAME,
            CTY.SHORT_NAME AS CTY_SHORT_NAME,
            APC.ID AS APC_ID,
            APC.QUANTITY AS APC_QUANTITY,
            APC.PRICE AS APC_PRICE,
            APC.USED AS APC_USED,
            APC.PLAY_DATE AS APC_DATE,
            APC.C_ID AS C_ID,
            C.NAME AS C_NAME
FROM FLIGHT F JOIN AIRPLANE AP ON F.AP_ID = AP.ID 
			JOIN AIRPLANE_CHAIR APC ON APC.AP_ID = AP.ID
            JOIN CHAIR C ON C.ID = APC.C_ID = C.ID
            JOIN CITY CT ON CT.ID = F.TO_CITY
            JOIN CITY CTY ON CTY.ID = F.FORM_CITY
            JOIN AIRLINE AL ON AL.ID = AP.AL_ID
WHERE F.ID = FLIGHTID;
END //
DELIMITER ;

